/* Generated by parena build -- VS0 domain 3, do not edit by hand. */
#include "parena_runtime.h"
#include <string.h>
#include <stdint.h>
#include <stdlib.h>
#include <math.h>

int on_bacon_puck_intangible_speed_pct();

int on_bacon_puck_intangible_speed_pct(void) {
    return 30;
}

