#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BUILD_DIR="${ROOT_DIR}/build"

mkdir -p "${BUILD_DIR}"

COMMON_FLAGS=(-std=c99 -D_DEFAULT_SOURCE -O2 -Wall -Wextra -I"${ROOT_DIR}/packages")

gcc "${COMMON_FLAGS[@]}" \
  -o "${BUILD_DIR}/red_garden_server" \
  "${ROOT_DIR}/apps/server/src/main.c" \
  "${ROOT_DIR}/packages/simulation/local_game.c" \
  -lm

gcc "${COMMON_FLAGS[@]}" \
  -o "${BUILD_DIR}/red_garden_bot" \
  "${ROOT_DIR}/apps/client/bot_main.c" \
  -lm

gcc "${COMMON_FLAGS[@]}" \
  -o "${BUILD_DIR}/red_garden_lobby" \
  "${ROOT_DIR}/apps/lobby/src/main.c" \
  "${ROOT_DIR}/packages/simulation/local_game.c" \
  -lSDL2 -lGL -lGLU -lm

gcc "${COMMON_FLAGS[@]}" \
  -o "${BUILD_DIR}/red_garden_matchmaker" \
  "${ROOT_DIR}/apps/matchmaker/src/main.c"

# NORTHSTAR §13 (2026-07-24 pivot): apps/arena is the product now -- this is
# its server-authoritative UDP counterpart (1v1 and N-player team-mode PvP).
# packages/common/mlp_infer.c (S170-228): arena_game.c's own arena_bot_tick now calls
# rl_policy_forward() (packages/common/rl_policy_weights.h, generated by
# scripts/export_rl_policy_to_c.py), which is header-inline but calls into mlp_forward()
# -- every binary linking arena_game.c needs this object now.
gcc "${COMMON_FLAGS[@]}" \
  -o "${BUILD_DIR}/red_garden_arena_server" \
  -include "${ROOT_DIR}/packages/simulation/bloodflower_mod_host.h" \
  -include "${ROOT_DIR}/packages/simulation/tree_passive_mod_host.h" \
  -include "${ROOT_DIR}/packages/simulation/build_template_mod_host.h" \
  -include "${ROOT_DIR}/packages/simulation/item_curriculum_mod_host.h" \
  -include "${ROOT_DIR}/packages/simulation/duck_smoke_bomb_mod_host.h" \
  -include "${ROOT_DIR}/packages/simulation/abraham_fireball_mod_host.h" \
  -include "${ROOT_DIR}/packages/simulation/bacon_puck_intangible_speed_mod_host.h" \
  "${ROOT_DIR}/apps/arena_server/src/main.c" \
  "${ROOT_DIR}/packages/simulation/arena_game.c" \
  "${ROOT_DIR}/packages/simulation/arena_ai_bridge.c" \
  "${ROOT_DIR}/packages/simulation/bloodflower_mod.c" \
  "${ROOT_DIR}/packages/simulation/tree_passive_mod.c" \
  "${ROOT_DIR}/packages/simulation/build_template_mod.c" \
  "${ROOT_DIR}/packages/simulation/item_curriculum_mod.c" \
  "${ROOT_DIR}/packages/simulation/duck_smoke_bomb_mod.c" \
  "${ROOT_DIR}/packages/simulation/abraham_fireball_mod.c" \
  "${ROOT_DIR}/packages/simulation/bacon_puck_intangible_speed_mod.c" \
  "${ROOT_DIR}/packages/common/mlp_infer.c" \
  -lm

# A real networked MOBA bot (not the sim's internal practice-mode brain) --
# the "22 bots in the pool" requirement.
# packages/common/mlp_infer.c (2026-07-29): rl_engage_nudge() in main.c now calls
# rl_policy_forward() (packages/common/rl_policy_weights.h) the same way arena_game.c's
# internal bot brain does -- this binary links mlp_infer.c directly for it, same reasoning
# as the arena_server build below.
gcc "${COMMON_FLAGS[@]}" \
  -o "${BUILD_DIR}/red_garden_arena_bot" \
  "${ROOT_DIR}/apps/arena_bot/src/main.c" \
  "${ROOT_DIR}/packages/common/mlp_infer.c" \
  -lm

# S170-186: this script never built apps/arena itself (the actual human SDL2/GL client --
# everything player-facing: shop panel, character pane, scoreboard, draft screen, etc.) --
# only scripts/build_arena.sh did, a fact this session found out the hard way after treating
# "bash scripts/build.sh exits 0" as proof the client itself compiled clean across many
# commits, when it had never actually been asked to. Folded in here so "the main build script
# passed" means what it says for every binary this repo ships, not just most of them.
# No -lGLU (see build_arena.sh's own original comment): the arena client is a shader-based
# (modern GL) renderer loading GL 3.x entry points itself via SDL_GL_GetProcAddress, unlike
# apps/lobby above, which needs GLU.
gcc -std=c99 -D_DEFAULT_SOURCE -O2 -Wall -Wextra -I"${ROOT_DIR}/packages" \
  -o "${BUILD_DIR}/red_garden_arena" \
  -include "${ROOT_DIR}/packages/simulation/bloodflower_mod_host.h" \
  -include "${ROOT_DIR}/packages/simulation/tree_passive_mod_host.h" \
  -include "${ROOT_DIR}/packages/simulation/build_template_mod_host.h" \
  -include "${ROOT_DIR}/packages/simulation/item_curriculum_mod_host.h" \
  -include "${ROOT_DIR}/packages/simulation/duck_smoke_bomb_mod_host.h" \
  -include "${ROOT_DIR}/packages/simulation/abraham_fireball_mod_host.h" \
  -include "${ROOT_DIR}/packages/simulation/bacon_puck_intangible_speed_mod_host.h" \
  "${ROOT_DIR}/apps/arena/src/main.c" \
  "${ROOT_DIR}/packages/simulation/arena_game.c" \
  "${ROOT_DIR}/packages/simulation/arena_replay.c" \
  "${ROOT_DIR}/packages/simulation/arena_ai_bridge.c" \
  "${ROOT_DIR}/packages/simulation/bloodflower_mod.c" \
  "${ROOT_DIR}/packages/simulation/tree_passive_mod.c" \
  "${ROOT_DIR}/packages/simulation/build_template_mod.c" \
  "${ROOT_DIR}/packages/simulation/item_curriculum_mod.c" \
  "${ROOT_DIR}/packages/simulation/duck_smoke_bomb_mod.c" \
  "${ROOT_DIR}/packages/simulation/abraham_fireball_mod.c" \
  "${ROOT_DIR}/packages/simulation/bacon_puck_intangible_speed_mod.c" \
  "${ROOT_DIR}/packages/common/mlp_infer.c" \
  "${ROOT_DIR}/packages/goldenband/gband.c" \
  "${ROOT_DIR}/packages/goldenband/gband_rig.c" \
  "${ROOT_DIR}/packages/goldenband/gskel.c" \
  "${ROOT_DIR}/packages/goldenband/gmesh.c" \
  "${ROOT_DIR}/packages/goldenband/gband_mesh_rig.c" \
  -lSDL2 -lGL -lm
